/**
 * Document.js — Mongoose Model
 *
 * Represents an AI-generated planning document for a project.
 * Created by the Blueprint Engine after generation.
 *
 * TODO: Implement full schema in Phase 2 — Documents / Blueprint Engine.
 *
 * Planned fields:
 *   - project        ObjectId ref → Project  (required)
 *   - type           Enum: 'BRD' | 'SRS' | 'UserStories' | 'UseCases' | 'DBSchema' |
 *                          'APISpec' | 'Architecture' | 'TestCases' | 'Roadmap'
 *   - title          String  (required)
 *   - content        String  (Markdown — generated by AI)
 *   - status         Enum: 'generating' | 'ready' | 'failed'
 *   - generation     ObjectId ref → Generation
 *   - createdAt / updatedAt  (timestamps: true)
 */
